---
- name: Crear script de cliente
  template:
    src: run-client.sh.j2
    dest: '/home/{{ ansible_user }}/chat/run-client.sh'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Crear script de conexión rápida
  template:
    src: connect.sh.j2
    dest: '/home/{{ ansible_user }}/connect.sh'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'
